#print the welcome message
welcomeMessage = ("\t\tWelcome to the Grocery list App")
print (welcomeMessage.upper())
#get the user input
input("\nDate and time: ")
print("\nYou currently have meat and cheese in your list")
print()
grocery=["meat","cheese"]
grocery.append(input("Type of food to add to the grocery list: "))
grocery.append(input("Type of food to add to the grocery list: "))
grocery.append(input("Type of food to add to the grocery list: "))
print("\nHere is your grocery list: ")
print(grocery)
print("\nHere is your grocery list sorted: ")
grocery.sort(reverse= 0)
print(grocery)
print("\nSimulating grocery shopping...")
print("\nCurrently have : 5 items")
print(grocery)
#user input 1
rem1= input("\nWhat did you just buy: ")
print("\nRemoving " + rem1 + " from your list...")
grocery.remove(rem1)
print()
print("\nCurrently have : 4 items")
print(grocery)
#user input 2
rem2= input("\nWhat did you just buy: ")
print("\nRemoving " + rem2 + " from your list...")
grocery.remove(rem2)
print()
print("\nCurrently have : 3 items")
print(grocery)
#user input 3
rem3= input("\nWhat did you just buy: ")
print("\nRemoving " + rem3 + " from your list...")
grocery.remove(rem3)
print()
print("\nCurrently have : 2 items")
print(grocery)
print()
print("\nSorry, the store is out of " + grocery[-1])
#Adding a grocery in the list\n",
add= input("\nWhat would you like instead: ")
grocery.remove(grocery[-1])
grocery.append(add)
print()
print("\nHere is what remains on your grocery list:")
print(grocery)